#!/usr/bin/env/python

import argparse
import glob
from refstis.basedark import make_basedark

#------------------------------------------------------------

def parse_args():
    '''
    Parse command line arguments.  Returns args object.
    '''
    parser = argparse.ArgumentParser()

    parser.add_argument('files', nargs='*',
                        help='input files to turn into reference file' )

    parser.add_argument('-o', dest='outname', type=str, default='basebias.fits',
                        help='output name for the reference file' )

    parser.add_argument('-b', dest='biasname', type=str, default='',
                        help='Bias file for calibration.' )

    args = parser.parse_args()
    return args

#------------------------------------------------------------

if __name__ == "__main__":
    args = parse_args()
    make_basedark( args.files, args.outname ) 
