#!/usr/bin/env python

import argparse
from refstis.basedark import make_basedark

#-------------------------------------------------------------------------------

def parse_args():
    '''
    Parse command line arguments.  Returns args object.
    '''

    parser = argparse.ArgumentParser()

    parser.add_argument('files',
                        nargs='*',
                        help='input files to turn into reference file')

    parser.add_argument('-o',
                        dest='outname',
                        type=str,
                        default='basebias.fits',
                        help='output name for the reference file')

    parser.add_argument('-b',
                        dest='biasname',
                        type=str,
                        default=None,
                        help='Bias file for calibration')

    return parser.parse_args()

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    args = parse_args()
    make_basedark(args.files, args.outname, args.biasname)
