#!/usr/bin/env/python

import argparse
import glob
from refstis.refbias import make_refbias

#------------------------------------------------------------

def parse_args():
    '''
    Parse command line arguments.  Returns args object.
    '''
    parser = argparse.ArgumentParser()

    parser.add_argument('files', nargs='*',
                        help='input files to turn into reference file' )

    parser.add_argument('-o', dest='outname', type=str, default='refbias.fits',
                        help='output name for the reference file' )

    args = parser.parse_args()
    return args

#------------------------------------------------------------

if __name__ == "__main__":
    args = parse_args()
    make_refbias( args.files, args.outname ) 
