#!/usr/bin/env python

import argparse
from refstis.weekbias import make_weekbias

#-------------------------------------------------------------------------------

def parse_args():
    '''
    Parse command line arguments.  Returns args object.
    '''

    parser = argparse.ArgumentParser()

    parser.add_argument('files',
                        nargs='*',
                        help='input files to turn into reference file')

    parser.add_argument('-o',
                        dest='outname',
                        type=str,
                        default='weekbias.fits',
                        help='output name for the reference file')

    parser.add_argument('-b',
                        dest='basebias',
                        type=str,
                        default='basebias.fits',
                        help='filename for the basebias used in final reference file')

    return parser.parse_args()

#-------------------------------------------------------------------------------

if __name__ == "__main__":
    args = parse_args()
    make_weekbias(args.files, args.outname, args.basebias)
