name: CI

on:
  push:
  pull_request:

env:
  # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
  PYTHONIOENCODING: UTF8

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: install conda
        uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5  # v4.0.1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          conda-remove-defaults: "true"

      - name: install hstcal
        run: |
          conda install -y -c conda-forge hstcal

      - name: install build
        run: |
          pip install .[test]

      - name: coverage configuration
        run: |
          pwd
          python -c "import refstis; print(refstis.__file__)"
          python -m pytest --collect-only -q

      - name: run tests
        run: |
          pytest -v
